# Выбираем базовый образ
FROM gcc:latest

# Устанавливаем необходимые пакеты
RUN apt-get update && apt-get install -y \
    gdb \
    socat \
    sqlite3 \
    libsqlite3-dev \
    openssl \
    libssl-dev

# Создаем рабочую директорию для вашего приложения
WORKDIR /app

# Копируем исходный код программы в образ
COPY ./task /app

# Компилируем программу
# Это пример, убедитесь, что указываете правильные флаги и файлы
RUN chmod +x task

# Определяем порт, который будет прослушиваться
EXPOSE 1234

# Команда для запуска программы с помощью socat при старте контейнера
CMD ["socat", "TCP-LISTEN:1234,reuseaddr,fork", "EXEC:./task"]