[package]
name = "back"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket ={ version="0.5.1",features = ["json"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cookie = "0.16"
dotenv = "0.15.0"